name = "homepage-sitemap-robots-txt"
main = "index.js"
compatibility_date = "2024-03-27"

# This locks in your routes so GitHub never overwrites them
routes = [
  { pattern = "www.eryc.my.id/*", zone_name = "eryc.my.id" },
  { pattern = "eryc.my.id/*", zone_name = "eryc.my.id" },
  { pattern = "www.eryc.my.id/assets/*", zone_name = "eryc.my.id" },
  { pattern = "*eryc.my.id/assets/llm.txt", zone_name = "eryc.my.id" },
  { pattern = "*eryc.my.id/assets/sitemap.xml", zone_name = "eryc.my.id" }
]
